/**
 * E2E スモークテスト
 *
 * Vite preview サーバーを起動し、実際にHTTPリクエストを送って:
 * 1. HTMLが返るか
 * 2. JS/CSSアセットが404にならないか
 * 3. index.htmlにマウントポイントがあるか
 * を確認する。
 *
 * ブラウザが利用可能な環境では Playwright テストに置き換え可能。
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { execSync, spawn, type ChildProcess } from 'child_process'
import { readFileSync } from 'fs'
import { resolve } from 'path'

const ROOT = resolve(__dirname, '..')
const DIST = resolve(ROOT, 'dist')
let server: ChildProcess
let baseUrl: string

beforeAll(async () => {
  // Build first
  execSync('npm run build', { cwd: ROOT, stdio: 'pipe' })

  // Start preview server
  server = spawn('npx', ['vite', 'preview', '--port', '4174', '--strictPort'], {
    cwd: ROOT,
    stdio: 'pipe',
  })

  baseUrl = 'http://localhost:4174/coc_editor/'

  // Wait for server to be ready
  await new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Preview server did not start')), 10000)
    const check = async () => {
      try {
        const res = await fetch(baseUrl)
        if (res.ok) {
          clearTimeout(timeout)
          resolve()
          return
        }
      } catch {}
      setTimeout(check, 300)
    }
    check()
  })
}, 30000)

afterAll(() => {
  server?.kill()
})

describe('E2E スモークテスト', () => {
  it('index.htmlが200を返す', async () => {
    const res = await fetch(baseUrl)
    expect(res.status).toBe(200)
  })

  it('HTMLにマウントポイント(#root)が含まれる', async () => {
    const res = await fetch(baseUrl)
    const html = await res.text()
    expect(html).toContain('id="root"')
  })

  it('HTMLにscriptタグが含まれる', async () => {
    const res = await fetch(baseUrl)
    const html = await res.text()
    expect(html).toMatch(/<script.*src=.*\.js/)
  })

  it('JSアセットが200を返す', async () => {
    const res = await fetch(baseUrl)
    const html = await res.text()
    const jsMatch = html.match(/src="([^"]*\.js)"/)
    expect(jsMatch).toBeTruthy()

    const jsUrl = new URL(jsMatch![1], baseUrl).href
    const jsRes = await fetch(jsUrl)
    expect(jsRes.status).toBe(200)
    const body = await jsRes.text()
    expect(body.length).toBeGreaterThan(1000)
  })

  it('CSSアセットが200を返す', async () => {
    const res = await fetch(baseUrl)
    const html = await res.text()
    const cssMatch = html.match(/href="([^"]*\.css)"/)
    expect(cssMatch).toBeTruthy()

    const cssUrl = new URL(cssMatch![1], baseUrl).href
    const cssRes = await fetch(cssUrl)
    expect(cssRes.status).toBe(200)
  })

  it('ビルド成果物のJSにシンタックスエラーがない', () => {
    const indexHtml = readFileSync(resolve(DIST, 'index.html'), 'utf-8')
    const jsMatch = indexHtml.match(/src="\.?\/?(coc_editor\/)?([^"]*\.js)"/)
    expect(jsMatch).toBeTruthy()

    // Extract the asset filename
    const assetPath = jsMatch![2].replace(/^coc_editor\//, '')
    const jsContent = readFileSync(resolve(DIST, assetPath), 'utf-8')

    // Basic syntax check: try to parse as a module (catches obvious errors)
    // If the JS file was generated by Vite, it should at least be parseable
    expect(jsContent).toContain('createApp')
    expect(jsContent).toContain('pinia')
  })
})
