import type { Scenario } from '../types/scenario';

/**
 * サンプルシナリオ「悪夢の館」
 * エンジンの動作確認用。典型的なCoC短編シナリオ構成。
 */
export function createSampleScenario(): Scenario {
  const now = new Date().toISOString();
  return {
    id: 'sample-nightmare-mansion',
    title: '悪夢の館',
    author: 'サンプル',
    era: '現代日本（202X年）',
    playerCount: '2〜4人',
    estimatedTime: '3〜4時間',
    synopsis: '探索者たちは、行方不明の友人・佐藤健一を探すため、郊外の洋館「黒澤邸」を訪れる。館の中では奇妙な現象が次々と起こり、やがて館に潜む恐るべき真実が明らかになる。',
    truth: '黒澤邸の地下には、かつて当主・黒澤源蔵が召喚した「闇に棲むもの」が封じられている。源蔵の孫娘・黒澤美咲は祖父の研究を引き継ぎ、「闇に棲むもの」に生贄を捧げることで不老の力を得ている。佐藤健一は最新の生贄候補として地下の祭壇に囚われている。',
    backgroundInfo: '黒澤邸は明治時代に建てられた洋館で、周囲の住民からは「呪われた館」と恐れられている。当主・黒澤源蔵は1960年代に謎の失踪を遂げ、以後は孫娘の美咲が一人で暮らしている。',
    keeperNotes: '探索者が地下に到達する前にDay1の夜を迎えると、佐藤の状態が悪化する。時間管理が重要。美咲は表向き協力的だが、探索者が地下に近づくと態度が変わる。',
    npcs: [
      {
        id: 'npc-misaki',
        name: '黒澤美咲',
        age: 28,
        occupation: '館の管理人（自称）',
        description: '黒澤邸に一人で暮らす若い女性。穏やかで上品な物腰だが、祖父の研究を引き継いだ狂信者。実年齢は90歳を超えている。',
        stats: { str: 45, con: 60, siz: 45, dex: 65, app: 80, int: 75, pow: 85, edu: 70, hp: 10, mp: 17, san: 0 },
        skills: { '隠密': 60, '説得': 70, 'クトゥルフ神話': 25, 'オカルト': 65 },
        traits: ['狂信的', '演技力が高い', '冷酷'],
        relations: [
          { targetId: 'npc-sato', type: '生贄', description: '次の儀式の生贄として監禁中' },
        ],
        initialKnowledge: ['地下祭壇の存在', '闇に棲むものの召喚方法', '佐藤の監禁場所'],
        initialLocationId: 'loc-entrance',
        schedule: [
          { time: 'Day1 午後', locationId: 'loc-entrance', activity: '探索者を出迎える' },
          { time: 'Day1 夕方', locationId: 'loc-study', activity: '書斎で儀式の準備' },
          { time: 'Day1 夜', locationId: 'loc-basement', activity: '地下で儀式を行う' },
        ],
        notes: '探索者が地下の存在に気づくまでは協力的に振る舞う。地下への入り口について聞かれると話を逸らす。',
      },
      {
        id: 'npc-sato',
        name: '佐藤健一',
        age: 25,
        occupation: '大学院生',
        description: '探索者たちの友人。民俗学の研究で黒澤邸を訪れ、美咲に捕らえられた。地下の祭壇に拘束されている。',
        stats: { str: 50, con: 45, siz: 55, dex: 50, app: 55, int: 70, pow: 50, edu: 75, hp: 10, mp: 10, san: 30 },
        skills: { '図書館': 65, '歴史': 60, 'オカルト': 40 },
        traits: ['知的好奇心旺盛', '衰弱している'],
        relations: [],
        initialKnowledge: ['黒澤源蔵の研究内容の一部', '地下に何かがいること'],
        initialLocationId: 'loc-basement',
        notes: 'Day1夜の儀式までに救出されなければ、SAN値が大幅に低下する。',
      },
      {
        id: 'npc-tanaka',
        name: '田中巡査',
        age: 45,
        occupation: '警察官',
        description: '最寄りの交番に勤務する巡査。黒澤邸については「近づかない方がいい」と警告する。',
        stats: { str: 65, con: 60, siz: 70, dex: 50, app: 45, int: 55, pow: 50, edu: 55, hp: 13, mp: 10, san: 50 },
        skills: { '射撃（拳銃）': 45, '法律': 40, '目星': 50 },
        traits: ['実直', '迷信深い'],
        relations: [],
        initialKnowledge: ['黒澤邸の噂', '過去の失踪事件'],
        initialLocationId: 'loc-town',
        notes: '探索者に助けを求められれば最終的に協力するが、館に入ることには非常に消極的。',
      },
    ],
    locations: [
      {
        id: 'loc-town',
        name: '町（交番周辺）',
        description: '黒澤邸から車で15分ほどの小さな町。交番があり、田中巡査に話を聞ける。',
        tags: ['屋外', '安全'],
        connectedLocationIds: ['loc-entrance'],
        clueIds: ['clue-rumors'],
        npcIds: ['npc-tanaka'],
        notes: '探索の起点。ここで情報収集してから館に向かうのが自然な流れ。',
      },
      {
        id: 'loc-entrance',
        name: '黒澤邸・玄関ホール',
        description: '重厚な木製の扉を抜けると、埃っぽい広いホールが広がる。大きな階段が二階へ続いている。壁には古い肖像画が並ぶ。',
        tags: ['屋内', '館'],
        connectedLocationIds: ['loc-town', 'loc-living', 'loc-study', 'loc-2f'],
        clueIds: ['clue-portrait'],
        npcIds: ['npc-misaki'],
        notes: '美咲が最初に探索者を迎える場所。',
      },
      {
        id: 'loc-living',
        name: '黒澤邸・居間',
        description: '暖炉のある広い居間。本棚やソファが置かれている。テーブルの上に新聞の切り抜きが散らばっている。',
        tags: ['屋内', '館'],
        connectedLocationIds: ['loc-entrance', 'loc-kitchen'],
        clueIds: ['clue-newspaper'],
        npcIds: [],
        notes: '',
      },
      {
        id: 'loc-study',
        name: '黒澤邸・書斎',
        description: '壁一面の本棚に古書が詰まった書斎。机の上には手記やメモが散乱している。一部の本は異様な記号で書かれている。',
        tags: ['屋内', '館', '重要'],
        connectedLocationIds: ['loc-entrance'],
        clueIds: ['clue-diary', 'clue-ritual-notes'],
        npcIds: [],
        notes: '核心に近い手がかりが集中する場所。美咲の夕方のスケジュールと重なるので、タイミングに注意。',
      },
      {
        id: 'loc-2f',
        name: '黒澤邸・二階',
        description: '長い廊下に複数の部屋が並ぶ。ほとんどは施錠されているが、ゲストルームと美咲の寝室に入れる。',
        tags: ['屋内', '館'],
        connectedLocationIds: ['loc-entrance'],
        clueIds: ['clue-photo', 'clue-key'],
        npcIds: [],
        notes: '美咲の寝室には鍵がかかっている。〈鍵開け〉または美咲から鍵を得る必要がある。',
      },
      {
        id: 'loc-kitchen',
        name: '黒澤邸・台所',
        description: '古びた台所。奥に食料庫への扉がある。食料庫の床に不自然な隙間がある。',
        tags: ['屋内', '館'],
        connectedLocationIds: ['loc-living', 'loc-basement'],
        clueIds: ['clue-trapdoor'],
        npcIds: [],
        notes: '地下への入口。〈目星〉で床の隙間に気づける。',
      },
      {
        id: 'loc-basement',
        name: '黒澤邸・地下祭壇',
        description: '湿った石段を降りると、異様な紋様が刻まれた広い空間に出る。中央に石の祭壇があり、周囲に黒いロウソクが並ぶ。奥に人影が見える。',
        tags: ['屋内', '館', '危険', '重要'],
        connectedLocationIds: ['loc-kitchen'],
        clueIds: ['clue-altar'],
        npcIds: ['npc-sato'],
        notes: 'シナリオのクライマックス。ここに来ると美咲が本性を現す。SANチェック（1/1D6）。',
      },
    ],
    clues: [
      {
        id: 'clue-rumors',
        name: '町の噂',
        description: '「黒澤邸では昔から人が消える」「夜になると変な声が聞こえる」という住民の噂。田中巡査は過去に3件の失踪事件を知っている。',
        isKey: false,
        initialLocationId: 'loc-town',
        discoverySkill: '情報収集',
        discoveryDifficulty: 'regular',
        leadsTo: ['clue-newspaper'],
        notes: '',
      },
      {
        id: 'clue-portrait',
        name: '玄関の肖像画',
        description: '1960年代の黒澤源蔵の肖像画。傍らに立つ少女が現在の美咲と瓜二つ。〈目星〉で年代の矛盾に気づく。',
        isKey: false,
        initialLocationId: 'loc-entrance',
        discoverySkill: '目星',
        discoveryDifficulty: 'hard',
        leadsTo: ['clue-photo'],
        notes: '美咲が不老であることの伏線。',
      },
      {
        id: 'clue-newspaper',
        name: '新聞の切り抜き',
        description: '過去30年間の近隣の失踪事件に関する新聞記事。すべて黒澤邸の近くで発生している。記事の日付はほぼ5年おき。',
        isKey: true,
        initialLocationId: 'loc-living',
        discoverySkill: '図書館',
        discoveryDifficulty: 'regular',
        leadsTo: ['clue-diary'],
        notes: '5年周期 = 生贄の周期。',
      },
      {
        id: 'clue-diary',
        name: '黒澤源蔵の手記',
        description: '源蔵の個人的な手記。「闇に棲むもの」との交信、召喚の試み、そして「永遠の命」への渇望が綴られている。後半は正気を失ったような筆跡になる。',
        isKey: true,
        initialLocationId: 'loc-study',
        discoverySkill: '図書館',
        discoveryDifficulty: 'regular',
        leadsTo: ['clue-ritual-notes'],
        notes: '読了で〈クトゥルフ神話〉+3、SANチェック（1/1D3）。',
      },
      {
        id: 'clue-ritual-notes',
        name: '儀式のメモ',
        description: '美咲が書いたと思われる最近のメモ。次の「奉納」の日時と手順が書かれている。日付は今夜。',
        isKey: true,
        initialLocationId: 'loc-study',
        discoverySkill: 'オカルト',
        discoveryDifficulty: 'hard',
        leadsTo: ['clue-altar'],
        notes: 'これを見つけると時間的緊迫感が生まれる。',
      },
      {
        id: 'clue-photo',
        name: '古い写真',
        description: '美咲の寝室で見つかる複数の写真。1970年代、1990年代、2010年代のものだが、どれにも同じ容姿の「美咲」が写っている。',
        isKey: false,
        initialLocationId: 'loc-2f',
        discoverySkill: '目星',
        discoveryDifficulty: 'regular',
        leadsTo: [],
        notes: '美咲の不老の決定的証拠。',
      },
      {
        id: 'clue-key',
        name: '地下室の鍵',
        description: '美咲の寝室の引き出しから見つかる古びた鍵。台所の食料庫の床にある隠し扉に合う。',
        isKey: true,
        initialLocationId: 'loc-2f',
        discoverySkill: '目星',
        discoveryDifficulty: 'hard',
        leadsTo: ['clue-trapdoor'],
        notes: '美咲の寝室は施錠されている。',
      },
      {
        id: 'clue-trapdoor',
        name: '隠し扉',
        description: '台所の食料庫の床にある隠し扉。〈目星〉で不自然な隙間に気づく。鍵がかかっているが、地下室の鍵で開く。',
        isKey: true,
        initialLocationId: 'loc-kitchen',
        discoverySkill: '目星',
        discoveryDifficulty: 'regular',
        leadsTo: ['clue-altar'],
        notes: '力ずくで開ける場合は〈STR〉ロール。',
      },
      {
        id: 'clue-altar',
        name: '地下の祭壇',
        description: '異界の紋様が刻まれた石の祭壇。中央に拘束された佐藤健一。壁面には「闇に棲むもの」を描いたと思しきレリーフ。SANチェック（1/1D6）。',
        isKey: true,
        initialLocationId: 'loc-basement',
        discoverySkill: undefined,
        leadsTo: [],
        notes: '地下に入れば自動的に発見。',
      },
    ],
    events: [
      {
        id: 'evt-welcome',
        name: '美咲の歓迎',
        description: '美咲が探索者を丁寧に出迎え、お茶を勧める。「佐藤さん？ 数日前にいらして、研究をされていましたが、もう帰られましたよ」と嘘をつく。',
        trigger: '探索者が玄関に到着したとき',
        outcome: '美咲の〈説得〉 vs 探索者の〈心理学〉。失敗すると美咲の嘘を信じる。',
        triggerCondition: { type: 'locationVisited', locationId: 'loc-entrance' },
        effects: [],
        isRepeatable: false,
        notes: '',
      },
      {
        id: 'evt-misaki-suspicious',
        name: '美咲の動揺',
        description: '探索者が地下の存在に関する手がかりを見つけたことに美咲が気づく。態度がわずかに変わり、「そろそろお帰りになった方が…」と促す。',
        trigger: '儀式のメモまたは隠し扉を発見したとき',
        outcome: '美咲が探索者を排除しようとし始める。',
        triggerCondition: {
          type: 'or',
          conditions: [
            { type: 'clueDiscovered', clueId: 'clue-ritual-notes' },
            { type: 'clueDiscovered', clueId: 'clue-trapdoor' },
          ],
        },
        effects: [
          { type: 'setFlag', flag: 'misaki_hostile', value: true },
        ],
        isRepeatable: false,
        notes: '',
      },
      {
        id: 'evt-basement-confrontation',
        name: '地下での対決',
        description: '探索者が地下祭壇に到達すると、美咲が現れ本性を現す。「あなたたちも生贄にしてあげましょう」。闇に棲むものの影が蠢き始める。',
        trigger: '地下祭壇に到達したとき',
        outcome: '最終対決。美咲を止めるか、儀式を阻止するか、佐藤を救出するか。',
        triggerCondition: { type: 'locationVisited', locationId: 'loc-basement' },
        effects: [
          { type: 'showMessage', message: '美咲が狂気の笑みを浮かべ、祭壇の紋様が赤く輝き始める。SANチェック（1/1D6）。' },
        ],
        isRepeatable: false,
        notes: '',
      },
      {
        id: 'evt-sato-rescued',
        name: '佐藤の救出',
        description: '探索者が佐藤の拘束を解き、救出に成功する。佐藤は衰弱しているが、地下で見たことを断片的に語る。',
        trigger: '地下で佐藤を発見し、救出を試みたとき',
        outcome: '佐藤から「闇に棲むもの」についての情報を得られる。',
        triggerCondition: {
          type: 'and',
          conditions: [
            { type: 'clueDiscovered', clueId: 'clue-altar' },
            { type: 'npcAlive', npcId: 'npc-sato' },
          ],
        },
        effects: [],
        isRepeatable: false,
        notes: '',
      },
    ],
    timeline: [
      {
        id: 'tl-afternoon',
        time: 'Day1 午後',
        description: '美咲が玄関で探索者を迎える。表向きは親切に振る舞い、館を案内する素振りを見せる。',
        effects: [],
        notes: '探索者の到着時点。',
      },
      {
        id: 'tl-evening',
        time: 'Day1 夕方',
        description: '美咲が書斎にこもり、儀式の最終準備を始める。館内に微かな詠唱の声が響く。',
        effects: [
          { type: 'setFlag', flag: 'chanting_heard', value: true },
          { type: 'showMessage', message: 'どこからか微かな詠唱の声が聞こえてくる…。' },
        ],
        notes: '探索者が書斎にいると美咲と遭遇する可能性あり。',
      },
      {
        id: 'tl-night-ritual',
        time: 'Day1 夜',
        description: '美咲が地下で儀式を開始する。佐藤の生命力が「闇に棲むもの」に捧げられ始める。',
        preventedBy: {
          type: 'or',
          conditions: [
            { type: 'flag', flag: 'misaki_hostile', operator: '==', value: true },
            { type: 'eventOccurred', eventId: 'evt-basement-confrontation' },
          ],
        },
        effects: [
          { type: 'showMessage', message: '地下から断末魔のような叫び声が響き渡る。' },
          { type: 'setNpcState', npcId: 'npc-sato', field: 'condition', value: '瀕死' },
        ],
        notes: 'この前に探索者が介入していなければ佐藤が危険な状態になる。',
      },
      {
        id: 'tl-night-late',
        time: 'Day1 深夜',
        description: '儀式が完了し、佐藤が死亡する。美咲は若返りの力を得る。',
        preventedBy: {
          type: 'or',
          conditions: [
            { type: 'eventOccurred', eventId: 'evt-sato-rescued' },
            { type: 'eventOccurred', eventId: 'evt-basement-confrontation' },
            { type: 'not', condition: { type: 'npcAlive', npcId: 'npc-sato' } },
          ],
        },
        effects: [
          { type: 'setNpcState', npcId: 'npc-sato', field: 'alive', value: false },
          { type: 'showMessage', message: '…静寂が訪れた。何かが終わってしまった、という確信が胸を過ぎる。' },
        ],
        notes: '最悪の結末。佐藤を救えなかった場合。',
      },
    ],
    createdAt: now,
    updatedAt: now,
  };
}
